### ISSUE TITLE
"Some studio files are missing/corrupted" error

### ISSUE THREAD

**Issue by Rawblocky** [MaximumADHD/Roblox-Studio-Mod-Manager#136]
I am getting this error the majority of the times I try launching RobloxStudioModManager. This is probably a ModManager issue, as when I open regular Roblox Studio, everything works fine. RobloxStudioModManager's "Force Reinstallation" does not fix this issue.

I don't know if this is related to the fact that RobloxStudioModManager has been getting a bunch of crash messages upon launching studio with it. It used to be "Studio.App.RobloxApplication.AbnormalTerminateMessage", now it's this.

![image](https://user-images.githubusercontent.com/26015280/185830755-0e266b7f-be5d-46ab-b44d-5db144d28187.png)

**Comment by randomizednum** [comment]
Have you tried using older versions?

**Comment by MaximumADHD** [comment]
Make sure you're on the latest release.
If it's still occurring, try forcing a reinstall of everything so that it has a clean slate.

**Comment by DionBlox1** [comment]
I have the same problem I tried what @MaximumADHD said but didint work.

**Comment by MaximumADHD** [comment]
> I have the same problem I tried what @MaximumADHD said but didint work. I was previously affected by #133 now affected the same at the post

Okay @DionBlox1, I want you to carefully and thoroughly make sure you follow all of these instructions because I don't like having to repeat myself:

1. Did you download the [newest release](https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/releases) of the mod manager?
2. Are you using the `LIVE` channel option?
3. Did you press `Launch Studio` **with** `Force Reinstallation` checked?
4. Did you let that installation complete fully?

If you have done all of the above, you should not have this issue anymore. Otherwise I need more information, screenshots, just anything that can help me reproduce this problem on my end.

Let me know if this works for you as well @Rawblocky!

**Comment by Rawblocky** [comment]
Forgot to add that a few days ago I downloaded the newest release and this issue no longer happens. I just used it for a few days before posting this because this error pops up randomly, but the newest release stopped this issue.
